#!/usr/bin/env bash

###############################################################################
##
## The following code is generated by the following SQL query:
##      select concat('./main.py ', wordContent, ' && sleep 1') as cmd from neodict_oxford5k_cd
##      where wordContent not in (select word from tc_words)
##
###############################################################################
